################################################################################
# Meta Data
################################################################################
url: "http://frankymartz.com"
author: Franky Martinez
title: Franky Martinez
subtitle: "Creative Developer"
email: frankymartz@gmail.com
description: "The code, art, and musings of Franky Martinez."

github: http://github.com/frankymartz
twitter: http://twitter.com/frankymartz
instagram: http://instagram.com/frankymartz


################################################################################
# Jekyll Configuration
################################################################################
source: ./_source
destination: public
exlude: [_drafts]

highlighter: pygments

permalink: /:categories/:title

markdown: kramdown

kramdown:
  input: GFM

