################################################################################
# FOR GOLDEN MASTER
################################################################################
url: "http://frankymartz.com"

future: false
show_drafts: false
lsi: true
limit_posts: 0

